### ISSUE TITLE
post hoc analysis file doesn't compile

### ISSUE THREAD

**Issue by cpmpercussion** [anucc/metatone-analysis#1]
some issue with the metatoneclassifier modules. gosh darn it.

**Comment by cpmpercussion** [comment]
this was an issue with the dependencies on MetatoneClassifier and the folder structure, fixed now, but it's kind of a hack. 

It might be better if metatone-analysis didn't depend on MetatoneClassifier in future.

**Comment by benswift** [comment]
Yep, agreed. Once we figure out the data structure stuff, everything else will just fall out from there I reckon.
